# Generated by Django 5.1.1 on 2026-03-19 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(default='Nepal', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('indoor', models.BooleanField(default=False)),
                ('family_friendly', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.destination')),
            ],
        ),
    ]
