# Generated by Django 5.1.1 on 2026-05-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
