# TREKKING ROUTES DATA WITH DAY-WISE ITINERARIES

TREKKING_ROUTES = {
    "poon_hill": {
        "name": "Poon Hill Trek",
        "region": "pokhara",
        "difficulty": "easy",
        "duration_days": 3,
        "distance_km": "16 km",
        "best_season": "October-November, March-April",
        "altitude_gain_m": "1530m",
        "highest_point": "3210m (Poon Hill viewpoint)",
        "description": "Classic short trek with stunning mountain sunrise and Himalayan panorama.",
        "custom_map_image": "/static/maps/poon_hill.jpg",
        "day_wise_itinerary": [
            {
                "day": 1,
                "title": "Pokhara to Nayapul to Birethanti",
                "distance": "6 km",
                "duration": "3-4 hours",
                "altitude": "1000m - 1050m",
                "highlights": "Scenic walk through rhododendron forests, local villages",
                "accommodation": "Birethanti (tea house/lodge)",
                "meal_options": ["Dal Bhat", "Momo", "Tea"],
                "map_location": "Birethanti, Kaski District",
                "custom_photo": "/static/maps/poon_hill_day1.jpg",
            },
            {
                "day": 2,
                "title": "Birethanti to Ghorepani",
                "distance": "5 km",
                "duration": "4-5 hours",
                "altitude": "1050m - 2680m",
                "highlights": "Gradual climb through forest, tea houses, local culture",
                "accommodation": "Ghorepani (mountain lodge)",
                "meal_options": ["Thakali Set", "Momo", "Local bread"],
                "map_location": "Ghorepani, Poon Hill Trail",
                "custom_photo": "/static/maps/poon_hill_day2.jpg",
            },
            {
                "day": 3,
                "title": "Ghorepani to Poon Hill to Pokhara",
                "distance": "5 km",
                "duration": "5-6 hours (including sunrise)",
                "altitude": "2680m - 3210m - 1000m",
                "highlights": "Sunrise at Poon Hill with 360° mountain views, descent to Pokhara",
                "accommodation": "Return to Pokhara",
                "meal_options": ["Mountain tea", "Snacks", "Breakfast", "Lunch en route"],
                "map_location": "Poon Hill Viewpoint, Annapurna Region",
                "custom_photo": "/static/maps/poon_hill_day3.jpg",
            },
        ],
    },
    "annapurna_base_camp": {
        "name": "Annapurna Base Camp Trek",
        "region": "pokhara",
        "difficulty": "moderate",
        "duration_days": 7,
        "distance_km": "45 km",
        "best_season": "September-November, March-May",
        "altitude_gain_m": "2550m",
        "highest_point": "4130m (Annapurna Base Camp)",
        "description": "Trekking route to the base camp of Annapurna massif with stunning views.",
        "custom_map_image": "/static/maps/annapurna_bc.jpg",
        "day_wise_itinerary": [
            {
                "day": 1,
                "title": "Pokhara to Ulleri",
                "distance": "7 km",
                "duration": "4-5 hours",
                "altitude": "1000m - 1960m",
                "highlights": "Steep climb with terraced fields, mountain forests",
                "accommodation": "Ulleri lodge",
                "meal_options": ["Dal Bhat", "Momo", "Tea"],
                "map_location": "Ulleri Village",
                "custom_photo": "/static/maps/abc_day1.jpg",
            },
            {
                "day": 2,
                "title": "Ulleri to Banthanti to Ghorepani",
                "distance": "11 km",
                "duration": "7-8 hours",
                "altitude": "1960m - 2680m",
                "highlights": "Forest trails, rhododendron views, local villages",
                "accommodation": "Ghorepani lodge",
                "meal_options": ["Thakali Set", "Veg curry", "Local tea"],
                "map_location": "Ghorepani",
                "custom_photo": "/static/maps/abc_day2.jpg",
            },
            {
                "day": 3,
                "title": "Ghorepani to Tatopani",
                "distance": "8 km",
                "duration": "5-6 hours",
                "altitude": "2680m - 1190m",
                "highlights": "Descent through rhododendron forests, hot spring village",
                "accommodation": "Tatopani natural hot spring resort",
                "meal_options": ["Thakali meals", "Fresh fish", "Local specialties"],
                "map_location": "Tatopani Hot Spring",
                "custom_photo": "/static/maps/abc_day3.jpg",
            },
            {
                "day": 4,
                "title": "Tatopani to Chhomrong",
                "distance": "10 km",
                "duration": "5-6 hours",
                "altitude": "1190m - 2680m",
                "highlights": "Steep climb through forests, suspension bridges",
                "accommodation": "Chhomrong lodge",
                "meal_options": ["Dal Bhat", "Momo", "Mountain tea"],
                "map_location": "Chhomrong",
                "custom_photo": "/static/maps/abc_day4.jpg",
            },
            {
                "day": 5,
                "title": "Chhomrong to Machapuchare Base Camp",
                "distance": "5 km",
                "duration": "4-5 hours",
                "altitude": "2680m - 3450m",
                "highlights": "Close-up views of Machapuchare (Fish Tail mountain)",
                "accommodation": "MBC lodge",
                "meal_options": ["Simple meals", "Soup", "Hot drinks"],
                "map_location": "Machapuchare Base Camp",
                "custom_photo": "/static/maps/abc_day5.jpg",
            },
            {
                "day": 6,
                "title": "Machapuchare BC to Annapurna Base Camp",
                "distance": "3 km",
                "duration": "3-4 hours",
                "altitude": "3450m - 4130m",
                "highlights": "Final push to ABC, 360° Annapurna range views",
                "accommodation": "ABC lodge",
                "meal_options": ["Mountain meals", "Soup", "Hot tea"],
                "map_location": "Annapurna Base Camp",
                "custom_photo": "/static/maps/abc_day6.jpg",
            },
            {
                "day": 7,
                "title": "Annapurna Base Camp to Pokhara",
                "distance": "28 km",
                "duration": "8-9 hours (descent + transport)",
                "altitude": "4130m - 1000m",
                "highlights": "Scenic descent, return to Pokhara",
                "accommodation": "Return to Pokhara",
                "meal_options": ["Mountain breakfast", "Packed lunch", "Celebration dinner"],
                "map_location": "Pokhara City",
                "custom_photo": "/static/maps/abc_day7.jpg",
            },
        ],
    },
    "langtang_valley": {
        "name": "Langtang Valley Trek",
        "region": "kathmandu",
        "difficulty": "moderate",
        "duration_days": 5,
        "distance_km": "30 km",
        "best_season": "March-May, September-November",
        "altitude_gain_m": "1430m",
        "highest_point": "3330m (Kyanjin Ri)",
        "description": "Beautiful valley trek with glaciers, forests, and mountain villages.",
        "custom_map_image": "/static/maps/langtang_valley.jpg",
        "day_wise_itinerary": [
            {
                "day": 1,
                "title": "Kathmandu to Sybrubesi",
                "distance": "10 km (car) + 2 km trek",
                "duration": "6-7 hours",
                "altitude": "1680m - 1460m",
                "highlights": "Drive to Trishuli, trek through terraced fields",
                "accommodation": "Sybrubesi lodge",
                "meal_options": ["Dal Bhat", "Noodles", "Local tea"],
                "map_location": "Sybrubesi, Nuwakot District",
                "custom_photo": "/static/maps/langtang_day1.jpg",
            },
            {
                "day": 2,
                "title": "Sybrubesi to Lama Hotel",
                "distance": "6 km",
                "duration": "4-5 hours",
                "altitude": "1460m - 2470m",
                "highlights": "Steep climb through bamboo, rhododendron forests",
                "accommodation": "Lama Hotel",
                "meal_options": ["Mountain meals", "Momo", "Hot soup"],
                "map_location": "Lama Hotel",
                "custom_photo": "/static/maps/langtang_day2.jpg",
            },
            {
                "day": 3,
                "title": "Lama Hotel to Langtang Village",
                "distance": "7 km",
                "duration": "4-5 hours",
                "altitude": "2470m - 3330m",
                "highlights": "Gradual climb with forest views, streams, prayer flags",
                "accommodation": "Langtang Village lodge",
                "meal_options": ["Thakali Set", "Vegetable curry", "Local bread"],
                "map_location": "Langtang Village",
                "custom_photo": "/static/maps/langtang_day3.jpg",
            },
            {
                "day": 4,
                "title": "Langtang Village - Acclimatization Day",
                "distance": "3 km (day hike)",
                "duration": "4-5 hours",
                "altitude": "3330m - 3650m",
                "highlights": "Hike to Kyanjin Ri viewpoint, panoramic mountain views",
                "accommodation": "Langtang Village lodge",
                "meal_options": ["Early breakfast", "Mountain snacks", "Hot tea"],
                "map_location": "Kyanjin Ri Viewpoint",
                "custom_photo": "/static/maps/langtang_day4.jpg",
            },
            {
                "day": 5,
                "title": "Langtang Village to Kathmandu",
                "distance": "13 km trek + drive",
                "duration": "5-6 hours trek + 2 hrs drive",
                "altitude": "3330m - 1460m - 1350m",
                "highlights": "Scenic descent, return to Kathmandu",
                "accommodation": "Return to Kathmandu",
                "meal_options": ["Mountain breakfast", "Lunch en route", "Dinner in Kathmandu"],
                "map_location": "Kathmandu City",
                "custom_photo": "/static/maps/langtang_day5.jpg",
            },
        ],
    },
    "everest_base_camp": {
        "name": "Everest Base Camp Trek",
        "region": "kathmandu",
        "difficulty": "hard",
        "duration_days": 14,
        "distance_km": "65 km",
        "best_season": "March-May, September-October",
        "altitude_gain_m": "2340m",
        "highest_point": "5364m (EBC)",
        "description": "Ultimate trekking adventure to the base camp of Mount Everest.",
        "custom_map_image": "/static/maps/everest_bc.jpg",
        "day_wise_itinerary": [
            {
                "day": 1,
                "title": "Kathmandu to Lukla (flight) to Phakding",
                "distance": "9 km trek",
                "duration": "1 hour flight + 3 hours trek",
                "altitude": "flight to 2680m, trek to 2610m",
                "highlights": "Scenic flight, entry to Everest region, Sherpa villages",
                "accommodation": "Phakding lodge",
                "meal_options": ["Sherpa meals", "Momo", "Local tea"],
                "map_location": "Phakding, Solukhumbu",
                "custom_photo": "/static/maps/ebc_day1.jpg",
            },
            {
                "day": 2,
                "title": "Phakding to Namche Bazaar",
                "distance": "11 km",
                "duration": "5-6 hours",
                "altitude": "2610m - 3440m",
                "highlights": "Steep climb to Sherpa capital, suspension bridges",
                "accommodation": "Namche Bazaar lodge",
                "meal_options": ["Dal Bhat", "Thakali meals", "Sherpa bread"],
                "map_location": "Namche Bazaar",
                "custom_photo": "/static/maps/ebc_day2.jpg",
            },
            {
                "day": 3,
                "title": "Namche Bazaar - Acclimatization",
                "distance": "4 km (day hike)",
                "duration": "3-4 hours",
                "altitude": "3440m - 3870m",
                "highlights": "Everest viewpoint hike, local monastery",
                "accommodation": "Namche lodge",
                "meal_options": ["Early breakfast", "Mountain snacks", "Hot tea"],
                "map_location": "Everest View, Namche",
                "custom_photo": "/static/maps/ebc_day3.jpg",
            },
            {
                "day": 4,
                "title": "Namche to Tengboche",
                "distance": "10 km",
                "duration": "5-6 hours",
                "altitude": "3440m - 3860m",
                "highlights": "Sacred Tengboche Monastery, Everest views",
                "accommodation": "Tengboche lodge",
                "meal_options": ["Mountain meals", "Momo", "Soup"],
                "map_location": "Tengboche Monastery",
                "custom_photo": "/static/maps/ebc_day4.jpg",
            },
            {
                "day": 5,
                "title": "Tengboche to Dingboche",
                "distance": "8 km",
                "duration": "4-5 hours",
                "altitude": "3860m - 4410m",
                "highlights": "High-altitude farming village, Ama Dablam views",
                "accommodation": "Dingboche lodge",
                "meal_options": ["Local meals", "Thakali Set", "Tea"],
                "map_location": "Dingboche",
                "custom_photo": "/static/maps/ebc_day5.jpg",
            },
            {
                "day": 6,
                "title": "Dingboche - Acclimatization",
                "distance": "5 km (day hike)",
                "duration": "4-5 hours",
                "altitude": "4410m - 4845m",
                "highlights": "Chukung valley viewpoint, acclimatization hike",
                "accommodation": "Dingboche lodge",
                "meal_options": ["Early breakfast", "Packed lunch", "Hot dinner"],
                "map_location": "Chukung Valley",
                "custom_photo": "/static/maps/ebc_day6.jpg",
            },
            {
                "day": 7,
                "title": "Dingboche to Lobuche East",
                "distance": "9 km",
                "duration": "4-5 hours",
                "altitude": "4410m - 4910m",
                "highlights": "High altitude, prayer flags, glaciated landscape",
                "accommodation": "Lobuche lodge",
                "meal_options": ["Simple meals", "Soup", "Hot drinks"],
                "map_location": "Lobuche East",
                "custom_photo": "/static/maps/ebc_day7.jpg",
            },
            {
                "day": 8,
                "title": "Lobuche to Gorak Shep",
                "distance": "5 km",
                "duration": "4-5 hours",
                "altitude": "4910m - 5140m",
                "highlights": "Final push to highest point before base camp",
                "accommodation": "Gorak Shep lodge",
                "meal_options": ["Mountain meals", "Soup", "Hot tea"],
                "map_location": "Gorak Shep",
                "custom_photo": "/static/maps/ebc_day8.jpg",
            },
            {
                "day": 9,
                "title": "Gorak Shep to Everest Base Camp",
                "distance": "5 km",
                "duration": "3-4 hours",
                "altitude": "5140m - 5364m",
                "highlights": "Reach EBC, world's highest base camp, achievement celebration",
                "accommodation": "Gorak Shep lodge",
                "meal_options": ["Early breakfast", "Hot drinks", "Packed snacks"],
                "map_location": "Everest Base Camp",
                "custom_photo": "/static/maps/ebc_day9.jpg",
            },
            {
                "day": 10,
                "title": "Gorak Shep to Pheriche",
                "distance": "9 km",
                "duration": "4-5 hours",
                "altitude": "5140m - 4370m",
                "highlights": "Descent with views, yak herds, glacial terrain",
                "accommodation": "Pheriche lodge",
                "meal_options": ["Thakali meals", "Yak cheese", "Local bread"],
                "map_location": "Pheriche",
                "custom_photo": "/static/maps/ebc_day10.jpg",
            },
            {
                "day": 11,
                "title": "Pheriche to Dingboche",
                "distance": "10 km",
                "duration": "4-5 hours",
                "altitude": "4370m - 4410m",
                "highlights": "Scenic descent, mountain vistas",
                "accommodation": "Dingboche lodge",
                "meal_options": ["Local meals", "Fresh vegetables", "Soup"],
                "map_location": "Dingboche",
                "custom_photo": "/static/maps/ebc_day11.jpg",
            },
            {
                "day": 12,
                "title": "Dingboche to Tengboche",
                "distance": "8 km",
                "duration": "4-5 hours",
                "altitude": "4410m - 3860m",
                "highlights": "Descent through forest, monastery visit",
                "accommodation": "Tengboche lodge",
                "meal_options": ["Thakali Set", "Momo", "Tea"],
                "map_location": "Tengboche",
                "custom_photo": "/static/maps/ebc_day12.jpg",
            },
            {
                "day": 13,
                "title": "Tengboche to Namche Bazaar",
                "distance": "10 km",
                "duration": "5-6 hours",
                "altitude": "3860m - 3440m",
                "highlights": "Final descent through forested trails",
                "accommodation": "Namche lodge",
                "meal_options": ["Mountain meals", "Rest day feast", "Local specialties"],
                "map_location": "Namche Bazaar",
                "custom_photo": "/static/maps/ebc_day13.jpg",
            },
            {
                "day": 14,
                "title": "Namche to Lukla to Kathmandu",
                "distance": "11 km trek + flight",
                "duration": "5-6 hours trek + 1 hour flight",
                "altitude": "3440m - 2680m - 1350m",
                "highlights": "Scenic descent, flight back, celebration",
                "accommodation": "Kathmandu",
                "meal_options": ["Mountain breakfast", "Lunch en route", "Celebration dinner"],
                "map_location": "Kathmandu",
                "custom_photo": "/static/maps/ebc_day14.jpg",
            },
        ],
    },
}
