TREKKING_ROUTES = {
    "poon_hill": {
        "id": "poon_hill",
        "name": "Poon Hill Trek",
        "region_label": "SCENIC",
        "difficulty": "Easy",
        "duration_days": 3,
        "max_altitude": "3,210m",
        "best_season": "Sep-Nov, Jan-May",
        "custom_map_image": "/api/trips/media/trek/poon_hill.svg",
        "summary": "A short and scenic trek with sunrise views and rhododendron forests.",
            "price_usd": 599,
            "price_npr": 78870,
        "highlights": [
            "Sunrise from Poon Hill",
            "Ghorepani tea houses",
            "Traditional Magar villages",
            "Mountain panoramas",
        ],
        "ordered_info": [
            "Start from Nayapul and stay at Tikhedhunga on day 1.",
            "Climb through Ulleri and forest section to reach Ghorepani on day 2.",
            "Hike early morning to Poon Hill viewpoint for sunrise on day 3.",
            "Return via Ghorepani route after breakfast.",
        ],
        "day_wise_itinerary": [
            {
                "day": 1,
                "route": "Nayapul to Tikhedhunga",
                "distance": "7km",
                "altitude": "1,540m",
                "highlights": "Starting point, river walk, local villages",
            },
            {
                "day": 2,
                "route": "Tikhedhunga to Ghorepani",
                "distance": "5.5km",
                "altitude": "2,750m",
                "highlights": "Steep climb, tea houses, forest trail",
            },
            {
                "day": 3,
                "route": "Ghorepani to Poon Hill and return",
                "distance": "6km",
                "altitude": "3,210m",
                "highlights": "Sunrise view, Himalayan panorama",
            },
        ],
    },
    "annapurna_base_camp": {
        "id": "annapurna_base_camp",
        "name": "Annapurna Base Camp Trek",
        "region_label": "MODERATE",
        "difficulty": "Moderate",
        "duration_days": 7,
        "max_altitude": "4,130m",
        "best_season": "Sep-Nov, Mar-May",
        "custom_map_image": "/api/trips/media/trek/annapurna_base_camp.svg",
        "summary": "Diverse landscapes from subtropical forest to alpine sanctuary.",
        "price_usd": 1199,
        "price_npr": 157740,
        "highlights": [
            "Annapurna Base Camp",
            "Modi Khola valley",
            "Rhododendron forests",
            "Mountain sanctuary",
        ],
        "ordered_info": [
            "Travel from Pokhara and begin at Nayapul.",
            "Climb through Jhinu and Deurali with gradual elevation gain.",
            "Reach Annapurna Base Camp and complete high-altitude viewpoint day.",
            "Descend safely through the same corridor to Nayapul.",
        ],
        "day_wise_itinerary": [
            {
                "day": 1,
                "route": "Pokhara to Nayapul",
                "distance": "35km",
                "altitude": "1,100m",
                "highlights": "Drive to trailhead, local bazaar",
            },
            {
                "day": 2,
                "route": "Nayapul to Jhinu",
                "distance": "10km",
                "altitude": "1,760m",
                "highlights": "Forest walk, hot spring",
            },
            {
                "day": 3,
                "route": "Jhinu to Deurali",
                "distance": "9km",
                "altitude": "3,230m",
                "highlights": "Waterfall, forest trail",
            },
            {
                "day": 4,
                "route": "Deurali to Annapurna Base Camp",
                "distance": "7km",
                "altitude": "4,130m",
                "highlights": "Alpine meadows, mountain views",
            },
            {
                "day": 5,
                "route": "ABC return to Deurali",
                "distance": "7km",
                "altitude": "3,230m",
                "highlights": "Sunrise at ABC",
            },
            {
                "day": 6,
                "route": "Deurali to Jhinu",
                "distance": "9km",
                "altitude": "1,760m",
                "highlights": "Downhill trek",
            },
            {
                "day": 7,
                "route": "Jhinu to Nayapul and return",
                "distance": "10km",
                "altitude": "1,100m",
                "highlights": "Return to Pokhara",
            },
        ],
    },
    "langtang_valley": {
        "id": "langtang_valley",
        "name": "Langtang Valley Trek",
        "region_label": "CULTURE + NATURE",
        "difficulty": "Moderate",
        "duration_days": 5,
        "max_altitude": "3,870m",
        "best_season": "All year (best Sep-May)",
        "custom_map_image": "/api/trips/media/trek/langtang_valley.svg",
        "summary": "Close-to-Kathmandu trek with Tamang culture and alpine scenery.",
        "price_usd": 899,
        "price_npr": 118410,
        "highlights": [
            "Tamang villages",
            "Langtang Lirung views",
            "Alpine forests",
            "Kyanjin Gompa",
        ],
        "ordered_info": [
            "Drive from Kathmandu to Syabrubesi as base gateway.",
            "Trek along river and bamboo forests to Lama Hotel.",
            "Continue to Langtang Village for mountain and cultural exposure.",
            "Spend one acclimatization day before return descent.",
        ],
        "day_wise_itinerary": [
            {
                "day": 1,
                "route": "Kathmandu to Syabrubesi",
                "distance": "40km",
                "altitude": "1,460m",
                "highlights": "Drive, Langtang river views",
            },
            {
                "day": 2,
                "route": "Syabrubesi to Lama Hotel",
                "distance": "10km",
                "altitude": "2,380m",
                "highlights": "Bamboo forest, ridge walk",
            },
            {
                "day": 3,
                "route": "Lama Hotel to Langtang Village",
                "distance": "8km",
                "altitude": "3,300m",
                "highlights": "Rhododendron forest, peak views",
            },
            {
                "day": 4,
                "route": "Langtang Village to Kyanjin Gompa",
                "distance": "5km",
                "altitude": "3,870m",
                "highlights": "Monastery area, glacier valley",
            },
            {
                "day": 5,
                "route": "Return trek to Syabrubesi",
                "distance": "18km",
                "altitude": "1,460m",
                "highlights": "Downhill descent",
            },
        ],
    },
    "everest_base_camp": {
        "id": "everest_base_camp",
        "name": "Everest Base Camp Trek",
        "region_label": "HIGH ALTITUDE",
        "difficulty": "Hard",
        "duration_days": 14,
        "max_altitude": "5,364m",
        "best_season": "Sep-May",
        "custom_map_image": "/api/trips/media/trek/everest_base_camp.svg",
        "summary": "World-famous expedition route with Sherpa culture and iconic Himalayan terrain.",
        "price_usd": 1599,
        "price_npr": 210570,
        "highlights": [
            "Everest Base Camp",
            "Khumbu valley",
            "Namche acclimatization",
            "Kala Patthar sunrise",
        ],
        "ordered_info": [
            "Take a mountain flight to Lukla and begin trek to Phakding.",
            "Reach Namche Bazaar and acclimatize before higher ascent.",
            "Move via Tengboche, Dingboche, Lobuche to Everest Base Camp.",
            "Descend gradually via the same corridor and return by flight.",
        ],
        "day_wise_itinerary": [
            {
                "day": 1,
                "route": "Kathmandu to Lukla",
                "distance": "Flight",
                "altitude": "2,860m",
                "highlights": "Mountain flight",
            },
            {
                "day": 2,
                "route": "Lukla to Phakding",
                "distance": "9km",
                "altitude": "2,610m",
                "highlights": "First acclimatization day",
            },
            {
                "day": 3,
                "route": "Phakding to Namche Bazaar",
                "distance": "11km",
                "altitude": "3,440m",
                "highlights": "Sherpa capital, market town",
            },
            {
                "day": 4,
                "route": "Acclimatization at Namche",
                "distance": "5km",
                "altitude": "3,440m",
                "highlights": "Acclimatization hike",
            },
            {
                "day": 5,
                "route": "Namche to Tengboche",
                "distance": "17km",
                "altitude": "3,867m",
                "highlights": "Monastery and mountain views",
            },
            {
                "day": 6,
                "route": "Tengboche to Dingboche",
                "distance": "12km",
                "altitude": "4,410m",
                "highlights": "Valley ascent",
            },
            {
                "day": 7,
                "route": "Dingboche to Lobuche",
                "distance": "11km",
                "altitude": "4,940m",
                "highlights": "High altitude progression",
            },
            {
                "day": 8,
                "route": "Lobuche to Gorakshep",
                "distance": "8km",
                "altitude": "5,164m",
                "highlights": "Glacial moraine",
            },
            {
                "day": 9,
                "route": "Gorakshep to Everest Base Camp",
                "distance": "8km",
                "altitude": "5,364m",
                "highlights": "Reach base camp",
            },
            {
                "day": 10,
                "route": "Kala Patthar sunrise and descend",
                "distance": "Variable",
                "altitude": "5,545m",
                "highlights": "Everest sunrise viewpoint",
            },
            {
                "day": 11,
                "route": "Descent to Pheriche",
                "distance": "16km",
                "altitude": "4,371m",
                "highlights": "Steady descent",
            },
            {
                "day": 12,
                "route": "Pheriche to Namche",
                "distance": "22km",
                "altitude": "3,440m",
                "highlights": "Downhill trek",
            },
            {
                "day": 13,
                "route": "Namche to Lukla",
                "distance": "28km",
                "altitude": "2,860m",
                "highlights": "Final descent",
            },
            {
                "day": 14,
                "route": "Lukla to Kathmandu",
                "distance": "Flight",
                "altitude": "1,400m",
                "highlights": "Return flight",
            },
        ],
    },
    "manaslu_circuit": {
        "id": "manaslu_circuit",
        "name": "Manaslu Circuit Trek",
        "region_label": "REMOTE HIMALAYA",
        "difficulty": "Hard",
        "duration_days": 12,
        "max_altitude": "5,106m",
        "best_season": "Sep-Nov, Mar-May",
        "custom_map_image": "/api/trips/media/trek/manaslu_circuit.svg",
        "summary": "Remote high-mountain circuit with rich Tibetan-influenced villages and dramatic mountain passes.",
        "price_usd": 1299,
        "price_npr": 170910,
        "area_story": "The route follows old salt-trade corridors where Gurung and Tibetan-influenced communities still preserve monastery rituals and seasonal pastoral life.",
        "local_lifestyle": "Villages run on tea-house hospitality, barley farming, yak herding, and prayer-centered community life.",
        "main_activities": [
            "High-pass crossing",
            "Monastery village exploration",
            "Tea-house cultural interaction",
            "Acclimatization ridge hikes",
        ],
        "region_foods": ["Tsampa porridge", "Butter tea", "Thenthuk", "Dal bhat with yak cheese"],
        "highlights": [
            "Larkya La Pass crossing",
            "Traditional Nubri and Tsum culture",
            "Remote suspension bridges",
            "Less-crowded Himalayan route",
        ],
        "ordered_info": [
            "Drive to Machha Khola and follow the Budi Gandaki valley upstream.",
            "Ascend gradually through Jagat, Deng, and Namrung for acclimatization.",
            "Reach Samagaon and complete acclimatization before high-pass section.",
            "Cross Larkya La and descend via Bimthang to complete the circuit.",
        ],
        "day_wise_itinerary": [
            {
                "day": 1,
                "route": "Kathmandu to Machha Khola",
                "distance": "Drive",
                "altitude": "930m",
                "highlights": "Riverside road journey",
            },
            {
                "day": 2,
                "route": "Machha Khola to Jagat",
                "distance": "22km",
                "altitude": "1,340m",
                "highlights": "River gorge trail and stone villages",
            },
            {
                "day": 3,
                "route": "Jagat to Deng",
                "distance": "20km",
                "altitude": "1,860m",
                "highlights": "Mixed forest and terraced settlements",
            },
            {
                "day": 4,
                "route": "Deng to Namrung",
                "distance": "19km",
                "altitude": "2,630m",
                "highlights": "Buddhist mani walls and mountain views",
            },
            {
                "day": 5,
                "route": "Namrung to Lho",
                "distance": "11km",
                "altitude": "3,180m",
                "highlights": "First close views of Manaslu",
            },
            {
                "day": 6,
                "route": "Lho to Samagaon",
                "distance": "8km",
                "altitude": "3,530m",
                "highlights": "Monasteries and high valley landscapes",
            },
            {
                "day": 7,
                "route": "Acclimatization at Samagaon",
                "distance": "6km",
                "altitude": "3,530m",
                "highlights": "Acclimatization hike toward Manaslu Base Camp",
            },
            {
                "day": 8,
                "route": "Samagaon to Samdo",
                "distance": "8km",
                "altitude": "3,860m",
                "highlights": "Open alpine valley section",
            },
            {
                "day": 9,
                "route": "Samdo to Dharamsala",
                "distance": "6km",
                "altitude": "4,460m",
                "highlights": "High camp preparation day",
            },
            {
                "day": 10,
                "route": "Dharamsala via Larkya La to Bimthang",
                "distance": "24km",
                "altitude": "5,106m",
                "highlights": "Major pass crossing and glacier views",
            },
            {
                "day": 11,
                "route": "Bimthang to Dharapani",
                "distance": "21km",
                "altitude": "1,960m",
                "highlights": "Long descent through rhododendron forests",
            },
            {
                "day": 12,
                "route": "Dharapani to Kathmandu",
                "distance": "Drive",
                "altitude": "1,400m",
                "highlights": "Return journey to city",
            },
        ],
    },
    "mardi_himal": {
        "id": "mardi_himal",
        "name": "Mardi Himal Trek",
        "region_label": "RIDGE ADVENTURE",
        "difficulty": "Moderate",
        "duration_days": 5,
        "max_altitude": "4,500m",
        "best_season": "Sep-Nov, Mar-May",
        "custom_map_image": "/api/trips/media/trek/mardi_himal.svg",
        "summary": "A compact ridge trek with dramatic Machhapuchhre views and forest camps.",
        "price_usd": 799,
        "price_npr": 105270,
        "area_story": "Once a shepherd trail, Mardi Himal route now connects trekkers with Gurung hillside settlements and newly developed community lodges.",
        "local_lifestyle": "Life follows mountain farming, lodge work, and seasonal trekking economy around Kande-Siding corridor.",
        "main_activities": [
            "Ridge sunrise hike",
            "Forest trail trekking",
            "Photography at high camp",
            "Community lodge stay",
        ],
        "region_foods": ["Dal bhat", "Gurung bread", "Momo", "Hot lemon ginger tea"],
        "highlights": [
            "Mardi Himal Base Camp viewpoint",
            "Machhapuchhre close-range panorama",
            "Rhododendron forests",
            "Less-crowded ridge route",
        ],
        "ordered_info": [
            "Drive from Pokhara to Kande and start ridge trail toward Australian Camp section.",
            "Trek through Forest Camp and Low Camp with gradual altitude gain.",
            "Reach High Camp and do pre-dawn hike toward Mardi viewpoint.",
            "Descend safely via Siding village and return to Pokhara roadhead.",
        ],
        "day_wise_itinerary": [
            {"day": 1, "route": "Pokhara to Kande to Forest Camp", "distance": "12km", "altitude": "2,550m", "highlights": "Stone steps, forest section, lodge entry"},
            {"day": 2, "route": "Forest Camp to Low Camp", "distance": "7km", "altitude": "3,050m", "highlights": "Rhododendron trail and open ridges"},
            {"day": 3, "route": "Low Camp to High Camp", "distance": "6km", "altitude": "3,580m", "highlights": "Expanding mountain panorama"},
            {"day": 4, "route": "High Camp to Mardi Viewpoint and descend", "distance": "11km", "altitude": "4,500m", "highlights": "Sunrise hike and ridge descent"},
            {"day": 5, "route": "Siding to Pokhara", "distance": "Drive", "altitude": "822m", "highlights": "Village trail end and city return"},
        ],
    },
    "upper_mustang": {
        "id": "upper_mustang",
        "name": "Upper Mustang Trek",
        "region_label": "TRANS-HIMALAYAN DESERT",
        "difficulty": "Hard",
        "duration_days": 10,
        "max_altitude": "3,840m",
        "best_season": "May-Oct",
        "custom_map_image": "/api/trips/media/trek/upper_mustang.svg",
        "summary": "Rain-shadow desert trek through walled villages, caves, and ancient Tibetan-Buddhist culture.",
        "price_usd": 1399,
        "price_npr": 184140,
        "area_story": "Known as the former Kingdom of Lo, this route preserves mud-walled settlements, sky caves, and ceremonial monastic traditions.",
        "local_lifestyle": "Communities rely on barley fields, yak and horse caravans, monastery calendars, and artisan crafts.",
        "main_activities": [
            "Walled city exploration",
            "Monastery heritage visit",
            "Desert canyon trekking",
            "Local homestay interaction",
        ],
        "region_foods": ["Barley roti", "Thakali khana", "Butter tea", "Dried apple snacks"],
        "highlights": [
            "Lo Manthang walled city",
            "Ancient sky caves",
            "Red cliff canyons",
            "Monastery murals",
        ],
        "ordered_info": [
            "Fly or drive to Jomsom and begin through Kagbeni permit check point.",
            "Ascend through Chele and Ghami villages with desert canyon terrain.",
            "Reach Lo Manthang and spend full day on monastery and cave exploration.",
            "Descend via alternate valley route and return through Jomsom corridor.",
        ],
        "day_wise_itinerary": [
            {"day": 1, "route": "Jomsom to Kagbeni", "distance": "11km", "altitude": "2,804m", "highlights": "Windy valley and permit entry"},
            {"day": 2, "route": "Kagbeni to Chele", "distance": "16km", "altitude": "3,050m", "highlights": "Cliff trails and village gates"},
            {"day": 3, "route": "Chele to Syangboche", "distance": "14km", "altitude": "3,800m", "highlights": "Pass crossings and desert views"},
            {"day": 4, "route": "Syangboche to Ghami", "distance": "11km", "altitude": "3,520m", "highlights": "Monastery stops and mani walls"},
            {"day": 5, "route": "Ghami to Tsarang", "distance": "10km", "altitude": "3,560m", "highlights": "Ancient settlement corridor"},
            {"day": 6, "route": "Tsarang to Lo Manthang", "distance": "13km", "altitude": "3,840m", "highlights": "Walled city arrival"},
            {"day": 7, "route": "Lo Manthang exploration day", "distance": "Local", "altitude": "3,840m", "highlights": "Monasteries, palace, caves"},
            {"day": 8, "route": "Lo Manthang to Drakmar", "distance": "17km", "altitude": "3,810m", "highlights": "Red cliffs and open plateau"},
            {"day": 9, "route": "Drakmar to Kagbeni", "distance": "22km", "altitude": "2,804m", "highlights": "Long descent and village tea houses"},
            {"day": 10, "route": "Kagbeni to Jomsom", "distance": "11km", "altitude": "2,720m", "highlights": "Trail completion"},
        ],
    },
    "gokyo_lakes": {
        "id": "gokyo_lakes",
        "name": "Gokyo Lakes Trek",
        "region_label": "GLACIAL LAKE CIRCUIT",
        "difficulty": "Hard",
        "duration_days": 11,
        "max_altitude": "5,357m",
        "best_season": "Sep-Nov, Mar-May",
        "custom_map_image": "/api/trips/media/trek/gokyo_lakes.svg",
        "summary": "High-altitude Sherpa route to turquoise glacial lakes and Gokyo Ri viewpoint.",
        "price_usd": 1699,
        "price_npr": 223770,
        "area_story": "The route links Sherpa trading villages, glacier corridors, and sacred high lakes respected by local communities.",
        "local_lifestyle": "Sherpa settlements blend mountaineering economy, yak pasture cycles, and monastery-centered social life.",
        "main_activities": [
            "Gokyo Ri sunrise climb",
            "Glacial lake exploration",
            "Sherpa village interaction",
            "High-altitude acclimatization hikes",
        ],
        "region_foods": ["Sherpa stew", "Potato rosti", "Yak cheese", "Ginger lemon honey tea"],
        "highlights": [
            "Gokyo Ri panorama",
            "Third and fourth Gokyo lakes",
            "Ngozumpa glacier edge",
            "Namche and Dole villages",
        ],
        "ordered_info": [
            "Fly to Lukla and follow standard trail to Namche for acclimatization.",
            "Divert from Namche corridor toward Dole, Machhermo, and Gokyo valley.",
            "Complete Gokyo Ri sunrise climb and optional higher lake side trips.",
            "Descend gradually through same valley and return by Lukla flight.",
        ],
        "day_wise_itinerary": [
            {"day": 1, "route": "Kathmandu to Lukla to Phakding", "distance": "Flight + 9km", "altitude": "2,610m", "highlights": "Mountain flight and first trail"},
            {"day": 2, "route": "Phakding to Namche Bazaar", "distance": "11km", "altitude": "3,440m", "highlights": "Sherpa gateway town"},
            {"day": 3, "route": "Namche acclimatization", "distance": "5km", "altitude": "3,440m", "highlights": "Acclimatization ridge walk"},
            {"day": 4, "route": "Namche to Dole", "distance": "11km", "altitude": "4,038m", "highlights": "Forest to alpine transition"},
            {"day": 5, "route": "Dole to Machhermo", "distance": "6km", "altitude": "4,470m", "highlights": "Yak pasture trail"},
            {"day": 6, "route": "Machhermo to Gokyo", "distance": "7km", "altitude": "4,790m", "highlights": "First lake views"},
            {"day": 7, "route": "Gokyo Ri sunrise and lake exploration", "distance": "8km", "altitude": "5,357m", "highlights": "Iconic summit panorama"},
            {"day": 8, "route": "Gokyo to Dole", "distance": "13km", "altitude": "4,038m", "highlights": "Glacier valley descent"},
            {"day": 9, "route": "Dole to Namche", "distance": "11km", "altitude": "3,440m", "highlights": "Return through rhododendron zone"},
            {"day": 10, "route": "Namche to Lukla", "distance": "18km", "altitude": "2,860m", "highlights": "Final trekking day"},
            {"day": 11, "route": "Lukla to Kathmandu", "distance": "Flight", "altitude": "1,400m", "highlights": "Return flight"},
        ],
    },
}
